### ISSUE TITLE
Ksuid generation fails when using datetime before 2014 with OverflowError

### ISSUE THREAD

**Issue by eddpascoal** [svix/python-ksuid#23]
**Specifications**
Python: 3.10
OS: Ubuntu 20.04.5 LTS

**Description**:
This is an expected issue or maybe a limitation as when generating a new ksuid based on a specific datetime it will only work  for datetimes from 2015. Please check the case scenarios below:

**Positive case scenario (before 2014):**
```
ksuid.Ksuid(datetime=datetime(2015, 2, 9, 10, 42, 28))
# result:  0CM1cVjc6DnPqpKaeGHOlWt0U9n```
```
**Negative case scenario (before 2015):**

```
ksuid.Ksuid(datetime=datetime(2014, 2, 9, 10, 42, 28))

File "/.../.venv/lib/python3.10/site-packages/ksuid/ksuid.py", line 92, in _inner_init
    return int.to_bytes(timestamp, self.TIMESTAMP_LENGTH_IN_BYTES, "big") + payload
OverflowError: can't convert negative int to unsigned
```

This is because:
```
datetime.datetime(2014, 2, 9, 10, 42, 28).timestamp() - EPOCH_STAMP
-8104252.0
```
as per source code
``` python
# (ksuid.py)
# KSUID's epoch starts more recently so that the 32-bit number space gives a
# significantly higher useful lifetime of around 136 years from March 2017.
# This number (14e8) was picked to be easy to remember.
```

Is this a real limitation or is there any way we can overcome this? without git fork, I mean.

**Comment by tasn** [comment]
This is unfortunately a limitation by the Ksuid itself, not the Svix implementation, check out: https://github.com/segmentio/ksuid#how-do-ksuids-work

That's what they designed it for.
