### ISSUE TITLE
Incorrect return type in timestamp method

### ISSUE THREAD

**Issue by TonySherman** [svix/python-ksuid#24]
In the [timestamp method](https://github.com/svix/python-ksuid/blob/main/ksuid/ksuid.py#L101), the type annotation is float but an int is actually returned. The timestamp method on the `KsuidMS` also has float as the return type.

Just causing my linter to nag me.

Happy to put up a PR if you'd like.

**Comment by tasn** [comment]
Whoops. Yes please. Though I think it should actually be a float, so the type is right, we just need to cast it.
It needs to be a float because:
1. That's how python usually does numerical timestamps.
2. KsuidMs has sub-second accuracy.
